const fs = require('node:fs')
const path = require('node:path')

const outMainDir = path.resolve(__dirname, '..', 'out', 'main')
fs.mkdirSync(outMainDir, { recursive: true })

const target = path.join(outMainDir, 'web.js')
const contents = `// Auto-generated by scripts/build-web.js
process.env.HEADLESS_SERVICE = process.env.HEADLESS_SERVICE ?? '1'
process.env.CHAT2API_WEB_UI = process.env.CHAT2API_WEB_UI ?? '1'
process.env.WEB_UI_ENABLED = process.env.WEB_UI_ENABLED ?? '1'

require('./index.js')
`

fs.writeFileSync(target, contents, 'utf8')
console.log('Wrote', target)